# Generated by Django 5.2.13 on 2026-04-21 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_address', models.TextField(blank=True, null=True)),
                ('project_investigator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_investigator_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_address', models.TextField(blank=True, null=True)),
                ('partner_investigator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_investigator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_investigator_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('proposal_title', models.CharField(blank=True, max_length=500, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
                ('registration_step', models.CharField(choices=[('1', 'Step 1'), ('2', 'Step 2'), ('3', 'Step 3'), ('4', 'Step 4'), ('5', 'Step 5'), ('completed', 'Completed')], default='1', max_length=20)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('admin', 'Admin'), ('owner', 'Owner')], default='participant', max_length=20)),
                ('dashboard_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
